# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: web_store
  pool: 5
  username: root
  password: Ass222Ass222
  #**socket: /opt/local/var/run/mysql5/mysqld.sock**# is needed just for MAC os
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: web_store_test
  pool: 5
  username: root
  password: Ass222Ass222
  #socket: **/opt/local/var/run/mysql5/mysqld.sock**

production:
  adapter: postgresql
  database: web_store_production

  #socket: **/opt/local/var/run/mysql5/mysqld.sock**
  #rake db:create to cmd
#more help for converting from sqlite to mysql)))  http://stackoverflow.com/questions/1670154/convert-a-ruby-on-rails-app-from-sqlite-to-mysql
#more info how to import db. https://www.youtube.com/watch?v=wOW9OhUPwUA I need to go to windows to copy it from there because my linux can not connect to my hdds in ntfs
